/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface WindowConstructor {
  appName?: string
  x?: number
  y?: number
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  maxWidth?: number
  maxHeight?: number
  resizable?: boolean
  title?: string
  icon?: string
  show?: boolean
  frame?: boolean
}
export declare class Window {
  constructor(options?: WindowConstructor | undefined | null)
  setTitle(title: string): void
  loadUrl(url: string): void
  loadHtml(url: string): void
  create(): void
  static getWebviewVersion(): string
}
