/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Window {
  constructor(options?: WindowOptions | undefined | null)
  setTitle(title: string): void
  loadUrl(url: string): void
  loadHtml(url: string): void
  create(callback: any): void
  static getWebviewVersion(): string
  static getLibVersion(): string
}

export interface WindowOptions {
  appName?: string
  x?: number
  y?: number
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  maxWidth?: number
  maxHeight?: number
  resizable?: boolean
  title?: string
  icon?: string
  show?: boolean
  frame?: boolean
  devtools?: boolean
}
